# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uro2pfuyVi6cokP6FFf3Ouev-w2BTTpe
"""

!pip install torch torchvision torchinfo tqdm seaborn scikit-learn

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import random_split

from torchvision import transforms

from sklearn.metrics import confusion_matrix

from tqdm import tqdm

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

#Téléchargement
!wget https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
!wget https://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz

#Décompression
!tar -xzf images.tar.gz
!tar -xzf annotations.tar.gz

#Vérification
print(os.listdir("images")[:5])
print(os.listdir("annotations"))

#Classe Dataset
class PetSegmentationDataset(Dataset):

    def __init__(self, root='.', split='train', img_size=256):

        self.root = root
        self.img_size = img_size

        self.img_transform = transforms.Compose([
            transforms.Resize((img_size,img_size)),
            transforms.ToTensor(),
            transforms.Normalize(
                [0.485,0.456,0.406],
                [0.229,0.224,0.225]
            )
        ])

        self.mask_transform = transforms.Compose([
            transforms.Resize(
                (img_size,img_size),
                interpolation=transforms.InterpolationMode.NEAREST
            )
        ])

        list_file = os.path.join(
            root,
            "annotations",
            "trainval.txt" if split=="train"
            else "test.txt"
        )

        with open(list_file) as f:
            self.names = [
                line.split()[0]
                for line in f.readlines()
            ]

    def __len__(self):
        return len(self.names)

    def __getitem__(self, idx):

        img = Image.open(
            os.path.join(
                self.root,
                "images",
                self.names[idx]+".jpg"
            )
        ).convert("RGB")

        mask = Image.open(
            os.path.join(
                self.root,
                "annotations",
                "trimaps",
                self.names[idx]+".png"
            )
        )

        img = self.img_transform(img)

        mask = torch.tensor(
            np.array(
                self.mask_transform(mask)
            ),
            dtype=torch.long
        ) - 1

        return img, mask

#Charger Dataset
dataset = PetSegmentationDataset(
    root=".",
    split="train"
)

print("Nombre d'images :", len(dataset))

#Afficher 4 exemples
fig, axes = plt.subplots(
    4,
    2,
    figsize=(8,12)
)

for i in range(4):

    img, mask = dataset[i]

    img_show = img.permute(
        1,2,0
    ).numpy()

    img_show = (
        img_show *
        np.array([0.229,0.224,0.225])
        +
        np.array([0.485,0.456,0.406])
    )

    axes[i,0].imshow(
        np.clip(img_show,0,1)
    )

    axes[i,0].set_title("Image")

    axes[i,1].imshow(mask)

    axes[i,1].set_title("Masque")

plt.tight_layout()
plt.show()

#Distribution des classes
from collections import Counter

counter = Counter()

for i in tqdm(range(len(dataset))):

    _, mask = dataset[i]

    mask = mask.numpy()

    unique, counts = np.unique(
        mask,
        return_counts=True
    )

    for u,c in zip(unique,counts):
        counter[u] += c

print(counter)

#Histogramme
plt.figure(figsize=(8,5))

plt.bar(
    counter.keys(),
    counter.values()
)

plt.xlabel("Classe")
plt.ylabel("Pixels")
plt.title("Distribution des classes")

plt.show()

#Pondération des classes
counts = np.array(
    list(counter.values())
)

weights = 1 / counts

weights = (
    weights /
    weights.sum()
)

class_weights = torch.tensor(
    weights,
    dtype=torch.float
).to(device)

print(class_weights)

#Q2 : Data Augmentation
import torchvision.transforms.functional as TF

class SegmentationAugmentation:

    def __call__(self,image,mask):

        if random.random() > 0.5:

            image = TF.hflip(image)
            mask = TF.hflip(mask)

        angle = random.randint(
            -20,
            20
        )

        image = TF.rotate(
            image,
            angle
        )

        mask = TF.rotate(
            mask,
            angle
        )

        image = TF.adjust_brightness(
            image,
            random.uniform(
                0.8,
                1.2
            )
        )

        return image, mask

#Visualisation Avant / Après
img = Image.open(
    "./images/Abyssinian_1.jpg"
).convert("RGB")

mask = Image.open(
    "./annotations/trimaps/Abyssinian_1.png"
)

aug = SegmentationAugmentation()

img_aug, mask_aug = aug(
    img,
    mask
)

plt.figure(figsize=(12,5))

plt.subplot(121)
plt.imshow(img)
plt.title("Original")

plt.subplot(122)
plt.imshow(img_aug)
plt.title("Augmentée")

plt.show()

#Q3 : Train / Validation / Test
full_dataset = PetSegmentationDataset(
    root=".",
    split="train"
)

n = len(full_dataset)

train_size = int(0.7*n)

val_size = int(0.15*n)

test_size = n - train_size - val_size

train_ds, val_ds, test_ds = random_split(
    full_dataset,
    [
        train_size,
        val_size,
        test_size
    ]
)

print(
    len(train_ds),
    len(val_ds),
    len(test_ds)
)

batch_size = 8

train_loader = DataLoader(
    train_ds,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_ds,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2
)

test_loader = DataLoader(
    test_ds,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2
)

#Q4 : ConvBlock
class ConvBlock(nn.Module):

    def __init__(
        self,
        in_ch,
        out_ch
    ):

        super().__init__()

        self.block = nn.Sequential(

            nn.Conv2d(
                in_ch,
                out_ch,
                3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(out_ch),

            nn.ReLU(inplace=True),

            nn.Conv2d(
                out_ch,
                out_ch,
                3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(out_ch),

            nn.ReLU(inplace=True)

        )

    def forward(self,x):

        return self.block(x)

#Q4 : SimpleUNet
class SimpleUNet(nn.Module):

    def __init__(
        self,
        in_channels=3,
        num_classes=3,
        base_features=32
    ):

        super().__init__()

        f = base_features

        self.enc1 = ConvBlock(
            in_channels,
            f
        )

        self.enc2 = ConvBlock(
            f,
            f*2
        )

        self.enc3 = ConvBlock(
            f*2,
            f*4
        )

        self.enc4 = ConvBlock(
            f*4,
            f*8
        )

        self.bottleneck = ConvBlock(
            f*8,
            f*16
        )

        self.pool = nn.MaxPool2d(2)

        self.up4 = nn.ConvTranspose2d(
            f*16,
            f*8,
            2,
            stride=2
        )

        self.dec4 = ConvBlock(
            f*16,
            f*8
        )

        self.up3 = nn.ConvTranspose2d(
            f*8,
            f*4,
            2,
            stride=2
        )

        self.dec3 = ConvBlock(
            f*8,
            f*4
        )

        self.up2 = nn.ConvTranspose2d(
            f*4,
            f*2,
            2,
            stride=2
        )

        self.dec2 = ConvBlock(
            f*4,
            f*2
        )

        self.up1 = nn.ConvTranspose2d(
            f*2,
            f,
            2,
            stride=2
        )

        self.dec1 = ConvBlock(
            f*2,
            f
        )

        self.out_conv = nn.Conv2d(
            f,
            num_classes,
            1
        )

    def forward(self,x):

        e1 = self.enc1(x)

        e2 = self.enc2(
            self.pool(e1)
        )

        e3 = self.enc3(
            self.pool(e2)
        )

        e4 = self.enc4(
            self.pool(e3)
        )

        b = self.bottleneck(
            self.pool(e4)
        )

        d4 = self.dec4(
            torch.cat(
                [self.up4(b),e4],
                dim=1
            )
        )

        d3 = self.dec3(
            torch.cat(
                [self.up3(d4),e3],
                dim=1
            )
        )

        d2 = self.dec2(
            torch.cat(
                [self.up2(d3),e2],
                dim=1
            )
        )

        d1 = self.dec1(
            torch.cat(
                [self.up1(d2),e1],
                dim=1
            )
        )

        return self.out_conv(d1)

from torchinfo import summary

model = SimpleUNet(in_channels=3, num_classes=3).to(device)
print(model)

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Trainable params:", trainable_params)

summary(model, input_size=(1,3,256,256))

#Q5
def dice_loss(pred, target, num_classes=3, smooth=1e-6):
    pred = F.softmax(pred, dim=1)
    loss = 0
    for c in range(num_classes):
        p = pred[:, c]
        t = (target == c).float()
        inter = (p*t).sum()
        union = p.sum() + t.sum()
        loss += 1 - (2*inter + smooth)/(union + smooth)
    return loss/num_classes

criterion_ce = nn.CrossEntropyLoss(weight=class_weights)

def combined_loss(pred, target, alpha=0.5):
    return alpha*criterion_ce(pred, target) + (1-alpha)*dice_loss(pred, target)

# Test de la fonction de perte combinée

images, masks = next(iter(train_loader))

images = images.to(device)
masks = masks.to(device)

# Prédictions du modèle
outputs = model(images)

# Calcul des différentes pertes
ce = criterion_ce(outputs, masks)
dice = dice_loss(outputs, masks)
loss = combined_loss(outputs, masks)

print(f"CrossEntropy Loss : {ce.item():.6f}")
print(f"Dice Loss         : {dice.item():.6f}")
print(f"Combined Loss     : {loss.item():.6f}")

#Q6
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=2
)

def train_one_epoch():

    model.train()

    running_loss = 0.0

    for images, masks in tqdm(train_loader):

        images = images.to(device)
        masks = masks.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = combined_loss(outputs, masks)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    return running_loss / len(train_loader)

def validate():

    model.eval()

    running_loss = 0.0

    with torch.no_grad():

        for images, masks in val_loader:

            images = images.to(device)
            masks = masks.to(device)

            outputs = model(images)

            loss = combined_loss(outputs, masks)

            running_loss += loss.item()

    return running_loss / len(val_loader)

best_loss = float("inf")

patience = 5

counter = 0

train_losses = []

val_losses = []

num_epochs = 30

for epoch in range(num_epochs):

    train_loss = train_one_epoch()

    val_loss = validate()

    scheduler.step(val_loss)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    print(
        f"Epoch [{epoch+1}/{num_epochs}] "
        f"Train Loss: {train_loss:.4f} "
        f"Validation Loss: {val_loss:.4f}"
    )

    if val_loss < best_loss:

        best_loss = val_loss

        torch.save(
            model.state_dict(),
            "best_unet.pth"
        )

        counter = 0

    else:

        counter += 1

        if counter >= patience:

            print("Early Stopping déclenché.")

            break

plt.figure(figsize=(8,5))

plt.plot(
    train_losses,
    label="Train Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.grid()

plt.show()

#Q7 : Fonction IoU et Dice
def compute_iou_dice(pred_mask, true_mask, num_classes=3):

    iou_per_class = []
    dice_per_class = []

    for cls in range(num_classes):

        pred_cls = (pred_mask == cls)
        true_cls = (true_mask == cls)

        intersection = (pred_cls & true_cls).sum().item()

        union = (pred_cls | true_cls).sum().item()

        iou = intersection / (union + 1e-6)

        dice = (
            2 * intersection
        ) / (
            pred_cls.sum().item()
            + true_cls.sum().item()
            + 1e-6
        )

        iou_per_class.append(iou)
        dice_per_class.append(dice)

    mIoU = np.mean(iou_per_class)
    mDice = np.mean(dice_per_class)

    return mIoU, mDice, iou_per_class, dice_per_class

#le meilleur modèle
model.load_state_dict(
    torch.load(
        "best_unet.pth",
        map_location=device
    )
)

model.eval()

#Évaluation sur le test set
all_preds = []
all_masks = []

ious = []
dices = []

with torch.no_grad():

    for images, masks in tqdm(test_loader):

        images = images.to(device)

        outputs = model(images)

        preds = torch.argmax(
            outputs,
            dim=1
        ).cpu()

        for p,m in zip(preds,masks):

            mIoU,mDice,_,_ = compute_iou_dice(
                p,
                m
            )

            ious.append(mIoU)
            dices.append(mDice)

        all_preds.extend(
            preds.numpy().flatten()
        )

        all_masks.extend(
            masks.numpy().flatten()
        )

print("mIoU =", np.mean(ious))
print("mDice =", np.mean(dices))

#Matrice de confusion
cm = confusion_matrix(
    all_masks,
    all_preds
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Prediction")
plt.ylabel("Ground Truth")

plt.title("Confusion Matrix")

plt.show()

cm = confusion_matrix(
    all_masks,
    all_preds
)

print(cm)

#Affichage des  6 segmentations
model.eval()

fig, axes = plt.subplots(
    6,
    3,
    figsize=(12,18)
)

shown = 0

with torch.no_grad():

    for images,masks in test_loader:

        images = images.to(device)

        outputs = model(images)

        preds = torch.argmax(
            outputs,
            dim=1
        ).cpu()

        for i in range(len(images)):

            if shown == 6:
                break

            img = images[i].cpu()

            img = img.permute(
                1,2,0
            ).numpy()

            img = (
                img *
                np.array([0.229,0.224,0.225])
                +
                np.array([0.485,0.456,0.406])
            )

            axes[shown,0].imshow(
                np.clip(img,0,1)
            )
            axes[shown,0].set_title("Image")

            axes[shown,1].imshow(
                masks[i]
            )
            axes[shown,1].set_title("GT")

            axes[shown,2].imshow(
                preds[i]
            )
            axes[shown,2].set_title("Prediction")

            shown += 1

        if shown == 6:
            break

plt.tight_layout()
plt.show()

#Partie 3 : Transfer Learning
from torchvision.models import (
    resnet50,
    ResNet50_Weights
)

#TransferUNet
class TransferUNet(nn.Module):

    def __init__(
        self,
        num_classes=3,
        freeze_encoder=True
    ):

        super().__init__()

        backbone = resnet50(
            weights=ResNet50_Weights.IMAGENET1K_V2
        )

        self.enc0 = nn.Sequential(
            backbone.conv1,
            backbone.bn1,
            backbone.relu
        )

        self.pool = backbone.maxpool

        self.enc1 = backbone.layer1
        self.enc2 = backbone.layer2
        self.enc3 = backbone.layer3
        self.enc4 = backbone.layer4

        if freeze_encoder:

            for module in [
                self.enc0,
                self.enc1,
                self.enc2,
                self.enc3,
                self.enc4
            ]:

                for p in module.parameters():
                    p.requires_grad=False

        self.up4 = nn.ConvTranspose2d(
            2048,
            1024,
            2,
            stride=2
        )

        self.dec4 = ConvBlock(
            2048,
            512
        )

        self.up3 = nn.ConvTranspose2d(
            512,
            256,
            2,
            stride=2
        )

        self.dec3 = ConvBlock(
            768,
            256
        )

        self.up2 = nn.ConvTranspose2d(
            256,
            128,
            2,
            stride=2
        )

        self.dec2 = ConvBlock(
            384,
            64
        )

        self.up1 = nn.ConvTranspose2d(
            64,
            32,
            2,
            stride=2
        )

        self.dec1 = ConvBlock(
            96,
            32
        )

        self.final_up = nn.ConvTranspose2d(
            32,
            32,
            2,
            stride=2
        )

        self.out = nn.Conv2d(
            32,
            num_classes,
            1
        )

    def forward(self,x):

        e0 = self.enc0(x)

        e1 = self.enc1(
            self.pool(e0)
        )

        e2 = self.enc2(e1)

        e3 = self.enc3(e2)

        e4 = self.enc4(e3)

        d4 = self.up4(e4)
        d4 = torch.cat([d4,e3],dim=1)
        d4 = self.dec4(d4)

        d3 = self.up3(d4)
        d3 = torch.cat([d3,e2],dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        d2 = torch.cat([d2,e1],dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        d1 = torch.cat([d1,e0],dim=1)
        d1 = self.dec1(d1)

        d1 = self.final_up(d1)

        return self.out(d1)

#Q8 : Vérification
model_tl = TransferUNet(
    freeze_encoder=True
).to(device)

from torchinfo import summary

summary(
    model_tl,
    input_size=(1,3,256,256)
)

#Q9
import time

model_tl = TransferUNet(
    freeze_encoder=True
).to(device)

optimizer_tl = torch.optim.Adam(
    filter(
        lambda p: p.requires_grad,
        model_tl.parameters()
    ),
    lr=1e-3
)

scheduler_tl = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_tl,
    mode="min",
    factor=0.5,
    patience=2
)

def train_tl_epoch():

    model_tl.train()

    running_loss = 0

    for images, masks in tqdm(train_loader):

        images = images.to(device)
        masks = masks.to(device)

        optimizer_tl.zero_grad()

        outputs = model_tl(images)

        loss = combined_loss(outputs, masks)

        loss.backward()

        optimizer_tl.step()

        running_loss += loss.item()

    return running_loss / len(train_loader)


def validate_tl():

    model_tl.eval()

    running_loss = 0

    with torch.no_grad():

        for images, masks in val_loader:

            images = images.to(device)
            masks = masks.to(device)

            outputs = model_tl(images)

            loss = combined_loss(outputs, masks)

            running_loss += loss.item()

    return running_loss / len(val_loader)

best_loss = float("inf")

train_losses_tl = []
val_losses_tl = []
epoch_times_tl = []

patience = 5
counter = 0
num_epochs = 10

for epoch in range(num_epochs):

    t0 = time.time()

    train_loss = train_tl_epoch()
    val_loss = validate_tl()

    epoch_times_tl.append(time.time() - t0)

    scheduler_tl.step(val_loss)

    train_losses_tl.append(train_loss)
    val_losses_tl.append(val_loss)

    print(
        f"Epoch [{epoch+1}/{num_epochs}] "
        f"Train Loss={train_loss:.4f} "
        f"Val Loss={val_loss:.4f}"
    )

    if val_loss < best_loss:

        best_loss = val_loss

        torch.save(
            model_tl.state_dict(),
            "best_transfer_frozen.pth"
        )

        counter = 0

    else:

        counter += 1

        if counter >= patience:
            print("Early stopping")
            break

plt.figure(figsize=(8, 5))

plt.plot(train_losses_tl, label="Train")
plt.plot(val_losses_tl, label="Validation")

plt.title("Transfer Learning — Encodeur Gelé")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend()
plt.grid()
plt.show()

model_tl.load_state_dict(
    torch.load(
        "best_transfer_frozen.pth",
        map_location=device
    )
)

model_tl.eval()

ious = []
dices = []

with torch.no_grad():

    for images, masks in tqdm(test_loader):

        images = images.to(device)

        outputs = model_tl(images)

        preds = torch.argmax(
            outputs,
            dim=1
        ).cpu()

        for p, m in zip(preds, masks):

            miou, mdice, _, _ = compute_iou_dice(p, m)

            ious.append(miou)
            dices.append(mdice)

tl_miou = np.mean(ious)
tl_mdice = np.mean(dices)
tl_epoch_time = np.mean(epoch_times_tl)

print("Frozen Encoder mIoU  :", tl_miou)
print("Frozen Encoder mDice :", tl_mdice)

model_ft = TransferUNet(
    freeze_encoder=False
).to(device)

optimizer_ft = torch.optim.Adam(

    [
        {
            "params":
                list(model_ft.enc0.parameters()) +
                list(model_ft.enc1.parameters()) +
                list(model_ft.enc2.parameters()) +
                list(model_ft.enc3.parameters()) +
                list(model_ft.enc4.parameters()),

            "lr": 1e-4,
            "weight_decay": 1e-4
        },

        {
            "params":
                list(model_ft.up4.parameters())      +
                list(model_ft.dec4.parameters())     +
                list(model_ft.up3.parameters())      +
                list(model_ft.dec3.parameters())     +
                list(model_ft.up2.parameters())      +
                list(model_ft.dec2.parameters())     +
                list(model_ft.up1.parameters())      +
                list(model_ft.dec1.parameters())     +
                list(model_ft.final_up.parameters()) +
                list(model_ft.out.parameters()),

            "lr": 1e-3,
            "weight_decay": 1e-4
        }
    ]
)

scheduler_ft = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_ft,
    mode="min",
    factor=0.5,
    patience=2
)

def train_ft_epoch():

    model_ft.train()

    running_loss = 0

    for images, masks in tqdm(train_loader):

        images = images.to(device)
        masks = masks.to(device)

        optimizer_ft.zero_grad()

        outputs = model_ft(images)

        loss = combined_loss(outputs, masks)

        loss.backward()

        optimizer_ft.step()

        running_loss += loss.item()

    return running_loss / len(train_loader)


def validate_ft():

    model_ft.eval()

    running_loss = 0

    with torch.no_grad():

        for images, masks in val_loader:

            images = images.to(device)
            masks = masks.to(device)

            outputs = model_ft(images)

            loss = combined_loss(outputs, masks)

            running_loss += loss.item()

    return running_loss / len(val_loader)

best_loss_ft = float("inf")

train_losses_ft = []
val_losses_ft = []
epoch_times_ft = []

patience_ft = 5
counter_ft = 0
num_epochs_ft = 10

for epoch in range(num_epochs_ft):

    t0 = time.time()

    train_loss = train_ft_epoch()
    val_loss = validate_ft()

    epoch_times_ft.append(time.time() - t0)

    scheduler_ft.step(val_loss)

    train_losses_ft.append(train_loss)
    val_losses_ft.append(val_loss)

    print(
        f"Epoch [{epoch+1}/{num_epochs_ft}] "
        f"Train Loss={train_loss:.4f} "
        f"Val Loss={val_loss:.4f}"
    )

    if val_loss < best_loss_ft:

        best_loss_ft = val_loss

        torch.save(
            model_ft.state_dict(),
            "best_transfer_finetuned.pth"
        )

        counter_ft = 0

    else:

        counter_ft += 1

        if counter_ft >= patience_ft:
            print("Early stopping")
            break

plt.figure(figsize=(8, 5))

plt.plot(train_losses_ft, label="Train")
plt.plot(val_losses_ft, label="Validation")

plt.title("Transfer Learning — Fine-Tuning Complet")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend()
plt.grid()
plt.show()

model_ft.load_state_dict(
    torch.load(
        "best_transfer_finetuned.pth",
        map_location=device
    )
)

model_ft.eval()

ious = []
dices = []

with torch.no_grad():

    for images, masks in tqdm(test_loader):

        images = images.to(device)

        outputs = model_ft(images)

        preds = torch.argmax(
            outputs,
            dim=1
        ).cpu()

        for p, m in zip(preds, masks):

            miou, mdice, _, _ = compute_iou_dice(p, m)

            ious.append(miou)
            dices.append(mdice)

ft_miou = np.mean(ious)
ft_mdice = np.mean(dices)
ft_epoch_time = np.mean(epoch_times_ft)

print("Fine-Tuning mIoU  :", ft_miou)
print("Fine-Tuning mDice :", ft_mdice)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(train_losses_tl, label="Train",      color="steelblue")
axes[0].plot(val_losses_tl,   label="Validation", color="orange")
axes[0].set_title("TransferUNet — Encodeur Gelé")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss")
axes[0].legend()
axes[0].grid()

axes[1].plot(train_losses_ft, label="Train",      color="steelblue")
axes[1].plot(val_losses_ft,   label="Validation", color="orange")
axes[1].set_title("TransferUNet — Fine-Tuning Complet")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].legend()
axes[1].grid()

plt.suptitle("Q9 — Comparaison des courbes de convergence", fontsize=13)
plt.tight_layout()
plt.show()

print("""
Observations Q9 :
  Encodeur gelé :
    - Convergence rapide car seul le décodeur est mis à jour
    - Peut plafonner si les features ResNet/ImageNet ne s'adaptent
      pas parfaitement à la tâche de segmentation d'animaux
  Fine-tuning (LR différentiel) :
    - Convergence plus lente mais l'encodeur s'adapte à la tâche
    - lr=1e-4 sur l'encodeur préserve les features pré-entraînées
      tout en les affinant doucement
    - lr=1e-3 sur le décodeur permet une adaptation rapide
    - Meilleur mIoU attendu si le dataset est suffisamment grand
""")

# Q10 : Recalcul métriques SimpleUNet
model.load_state_dict(
    torch.load(
        "best_unet.pth",
        map_location=device
    )
)

model.eval()

ious_simple = []
dices_simple = []

with torch.no_grad():

    for images, masks in tqdm(test_loader):

        images = images.to(device)

        preds = torch.argmax(
            model(images),
            dim=1
        ).cpu()

        for p, m in zip(preds, masks):

            miou, mdice, _, _ = compute_iou_dice(p, m)

            ious_simple.append(miou)
            dices_simple.append(mdice)

simple_miou  = float(np.mean(ious_simple))
simple_mdice = float(np.mean(dices_simple))

print("SimpleUNet mIoU  :", simple_miou)
print("SimpleUNet mDice :", simple_mdice)

#Q10 : Mesure du temps d'inférence (ms/image)

 def mesure_inference(model, loader, device):

    model.eval()

    t0 = time.time()
    n = 0

    with torch.no_grad():

        for images, _ in loader:

            model(images.to(device))

            n += images.size(0)

    return (time.time() - t0) / n * 1000


simple_infer = mesure_inference(model,    test_loader, device)
tl_infer     = mesure_inference(model_tl, test_loader, device)
ft_infer     = mesure_inference(model_ft, test_loader, device)

print(f"SimpleUNet     : {simple_infer:.2f} ms/image")
print(f"Encodeur gelé  : {tl_infer:.2f} ms/image")
print(f"Fine-Tuning    : {ft_infer:.2f} ms/image")

# Q10 : Calcul du nombre de paramètres


simple_params   = sum(p.numel() for p in model.parameters())

tl_params_total = sum(p.numel() for p in model_tl.parameters())
tl_params_train = sum(
    p.numel() for p in model_tl.parameters()
    if p.requires_grad
)

ft_params_total = sum(p.numel() for p in model_ft.parameters())

print(f"SimpleUNet     — total : {simple_params:,}")
print(f"Encodeur gelé  — total : {tl_params_total:,}  |  entraînés : {tl_params_train:,}")
print(f"Fine-Tuning    — total : {ft_params_total:,}")

#Q10 : Construction et affichage du tableau


data = {
    "Modèle": [
        "SimpleUNet\n(from scratch)",
        "TransferUNet\nEncodeur gelé",
        "TransferUNet\nFine-tuning"
    ],
    "mIoU": [
        f"{simple_miou:.4f}",
        f"{float(tl_miou):.4f}",
        f"{float(ft_miou):.4f}"
    ],
    "mDice": [
        f"{simple_mdice:.4f}",
        f"{float(tl_mdice):.4f}",
        f"{float(ft_mdice):.4f}"
    ],
    "Params totaux": [
        f"{simple_params:,}",
        f"{tl_params_total:,}",
        f"{ft_params_total:,}"
    ],
    "Params entraînés": [
        f"{simple_params:,}",
        f"{tl_params_train:,}",
        f"{ft_params_total:,}"
    ],
    "Temps/epoch (s)": [
        "—",
        f"{tl_epoch_time:.1f}",
        f"{ft_epoch_time:.1f}"
    ],
    "Inférence (ms/img)": [
        f"{simple_infer:.2f}",
        f"{tl_infer:.2f}",
        f"{ft_infer:.2f}"
    ]
}

df = pd.DataFrame(data)

print("\n" + "=" * 75)
print("Q10 — TABLEAU COMPARATIF FINAL")
print("=" * 75)
print(df.to_string(index=False))

#Q10 : Affichage graphique du tableau


fig, ax = plt.subplots(figsize=(15, 3))

ax.axis("off")

table = ax.table(
    cellText  = df.values,
    colLabels = df.columns,
    cellLoc   = "center",
    loc       = "center"
)

table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1, 2.5)

for j in range(len(df.columns)):
    table[0, j].set_facecolor("#2c3e50")
    table[0, j].set_text_props(color="white", fontweight="bold")

for i in range(1, 4):
    couleur = "#f0f4f8" if i % 2 == 1 else "#dce8f0"
    for j in range(len(df.columns)):
        table[i, j].set_facecolor(couleur)

plt.title(
    "Q10 — Tableau Comparatif : SimpleUNet vs TransferUNet",
    fontsize=13,
    fontweight="bold",
    pad=20
)

plt.tight_layout()
plt.show()