# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yE_7mOQYh2D4_EhTzrsXIEnEuvU8M-R
"""

!pip install torch torchvision pycocotools nltk tqdm --quiet
!pip install rouge-score --quiet

import os
import re
import json
import time
import random
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from collections import Counter
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import resnet50, ResNet50_Weights

from pycocotools.coco import COCO

import nltk
nltk.download('punkt', quiet=True)
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device :", device)
print("GPU :", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

#Téléchargement du subset COCO 2017
import os, zipfile

os.makedirs("coco/images/train2017", exist_ok=True)
os.makedirs("coco/images/val2017",   exist_ok=True)
os.makedirs("coco/annotations",      exist_ok=True)

# Annotations
!wget -q http://images.cocodataset.org/annotations/annotations_trainval2017.zip
!unzip -q annotations_trainval2017.zip -d coco/
!rm annotations_trainval2017.zip

# Images train (subset ~5000 images via wget liste ou wget direct)
# Pour Colab on télécharge directement les images train et val
!wget -q http://images.cocodataset.org/zips/train2017.zip
!unzip -q train2017.zip -d coco/images/
!rm train2017.zip

!wget -q http://images.cocodataset.org/zips/val2017.zip
!unzip -q val2017.zip -d coco/images/
!rm val2017.zip

print("Annotations :", os.listdir("coco/annotations"))
print("Train images:", len(os.listdir("coco/images/train2017")))
print("Val   images:", len(os.listdir("coco/images/val2017")))

class Vocabulary:

    def __init__(self, freq_threshold=5):

        self.freq_threshold = freq_threshold

        self.itos = {
            0: '<PAD>',
            1: '<SOS>',
            2: '<EOS>',
            3: '<UNK>'
        }

        self.stoi = {v: k for k, v in self.itos.items()}

    def __len__(self):
        return len(self.itos)

    @staticmethod
    def tokenize(text):
        return re.findall(r"\w+", text.lower())

    def build(self, captions_list):

        counter = Counter()

        for caps in captions_list:
            for cap in caps:
                counter.update(self.tokenize(cap))

        idx = 4

        for word, freq in counter.items():
            if freq >= self.freq_threshold:
                self.stoi[word] = idx
                self.itos[idx]  = word
                idx += 1

        print(f"Vocabulary size : {len(self.itos)} tokens")

    def numericalize(self, caption, max_len=50):

        tokens = [
            self.stoi.get(w, self.stoi['<UNK>'])
            for w in self.tokenize(caption)
        ]

        seq = (
            [self.stoi['<SOS>']] +
            tokens[:max_len - 2]  +
            [self.stoi['<EOS>']]
        )

        seq += [self.stoi['<PAD>']] * (max_len - len(seq))

        return seq

# Charger les annotations COCO train
coco_train = COCO("coco/annotations/captions_train2017.json")

# Récupérer toutes les captions
all_caps = [
    [coco_train.anns[aid]['caption'] for aid in coco_train.getAnnIds(imgIds=img_id)]
    for img_id in coco_train.getImgIds()
]

# Construire le vocabulaire
vocab = Vocabulary(freq_threshold=5)
vocab.build(all_caps)

print(f"\nTaille du vocabulaire : {len(vocab)}")

# 20 mots les plus fréquents
counter_all = Counter()
for caps in all_caps:
    for cap in caps:
        counter_all.update(Vocabulary.tokenize(cap))

print("\nTop 20 mots les plus fréquents :")
for word, freq in counter_all.most_common(20):
    print(f"  {word:15s} : {freq:,}")

# Distribution des longueurs de captions
lengths = [
    len(Vocabulary.tokenize(cap))
    for caps in all_caps
    for cap in caps
]

plt.figure(figsize=(10, 4))
plt.hist(lengths, bins=40, color='steelblue', edgecolor='black')
plt.xlabel("Longueur de la caption (tokens)")
plt.ylabel("Fréquence")
plt.title("Q1 — Distribution des longueurs de captions")
plt.axvline(x=50, color='red', linestyle='--', label='max_len=50')
plt.legend()
plt.tight_layout()
plt.show()

print(f"\nLongueur max : {max(lengths)}")
print(f"Longueur moyenne : {np.mean(lengths):.1f}")
print(f"Percentile 95 : {np.percentile(lengths, 95):.0f}")
print("""
Justification max_len=50 :
  Le percentile 95 des longueurs est < 50 tokens.
  max_len=50 couvre 95% des captions sans gaspiller de mémoire.
  Les captions plus longues sont tronquées (très rares).
""")

# Q2 : Classe COCOCaptionDataset

class COCOCaptionDataset(Dataset):

    def __init__(
        self,
        root,
        ann_file,
        vocab,
        split='train',
        img_size=224,
        max_len=50
    ):

        self.root    = root
        self.vocab   = vocab
        self.max_len = max_len
        self.coco    = COCO(ann_file)
        self.ids     = list(self.coco.anns.keys())

        if split == 'train':
            self.transform = transforms.Compose([
                transforms.Resize((img_size, img_size)),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(
                    [0.485, 0.456, 0.406],
                    [0.229, 0.224, 0.225]
                )
            ])
        else:
            self.transform = transforms.Compose([
                transforms.Resize((img_size, img_size)),
                transforms.ToTensor(),
                transforms.Normalize(
                    [0.485, 0.456, 0.406],
                    [0.229, 0.224, 0.225]
                )
            ])

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, idx):

        ann      = self.coco.anns[self.ids[idx]]
        img_id   = ann['image_id']
        img_info = self.coco.loadImgs(img_id)[0]

        img = Image.open(
            os.path.join(self.root, img_info['file_name'])
        ).convert('RGB')

        img = self.transform(img)

        caption = torch.tensor(
            self.vocab.numericalize(ann['caption'], self.max_len),
            dtype=torch.long
        )

        return img, caption

#Q2 : collate_fn + DataLoaders + 3 exemples


def collate_fn(batch):

    # Trier par longueur décroissante (requis pour pack_padded_sequence)
    batch.sort(key=lambda x: (x[1] != 0).sum(), reverse=True)

    images, captions = zip(*batch)

    images   = torch.stack(images, 0)
    captions = torch.stack(captions, 0)

    lengths = torch.tensor(
        [(cap != 0).sum().item() for cap in captions],
        dtype=torch.long
    )

    return images, captions, lengths


# Datasets
train_dataset = COCOCaptionDataset(
    root     = "coco/images/train2017",
    ann_file = "coco/annotations/captions_train2017.json",
    vocab    = vocab,
    split    = 'train'
)

val_dataset = COCOCaptionDataset(
    root     = "coco/images/val2017",
    ann_file = "coco/annotations/captions_val2017.json",
    vocab    = vocab,
    split    = 'val'
)

# Subset pour Colab (5000 train / 500 val)
train_subset = torch.utils.data.Subset(
    train_dataset,
    range(min(5000, len(train_dataset)))
)

val_subset = torch.utils.data.Subset(
    val_dataset,
    range(min(500, len(val_dataset)))
)

BATCH_SIZE = 32

train_loader = DataLoader(
    train_subset,
    batch_size  = BATCH_SIZE,
    shuffle     = True,
    num_workers = 2,
    collate_fn  = collate_fn,
    pin_memory  = True
)

val_loader = DataLoader(
    val_subset,
    batch_size  = BATCH_SIZE,
    shuffle     = False,
    num_workers = 2,
    collate_fn  = collate_fn,
    pin_memory  = True
)

print(f"Train batches : {len(train_loader)}")
print(f"Val   batches : {len(val_loader)}")

# Afficher 3 exemples
images, captions, lengths = next(iter(train_loader))

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i in range(3):

    img_np = images[i].permute(1, 2, 0).numpy()
    img_np = img_np * np.array([0.229, 0.224, 0.225]) \
                    + np.array([0.485, 0.456, 0.406])

    # Décoder la caption
    cap_decoded = ' '.join([
        vocab.itos.get(idx.item(), '<UNK>')
        for idx in captions[i]
        if idx.item() not in [
            vocab.stoi['<PAD>'],
            vocab.stoi['<SOS>'],
            vocab.stoi['<EOS>']
        ]
    ])

    axes[i].imshow(np.clip(img_np, 0, 1))
    axes[i].set_title(cap_decoded, fontsize=8, wrap=True)
    axes[i].axis('off')

plt.suptitle("Q2 — 3 exemples image + caption décodée", fontsize=12)
plt.tight_layout()
plt.show()

# Q3 : ImageEncoder (ResNet50)


class ImageEncoder(nn.Module):

    def __init__(self, embed_size=256, fine_tune=False):

        super().__init__()

        resnet   = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)

        # Supprimer la tête de classification (garder jusqu'à layer4)
        modules  = list(resnet.children())[:-2]
        self.resnet = nn.Sequential(*modules)   # sortie : (B, 2048, 7, 7)

        self.adaptive_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc            = nn.Linear(2048, embed_size)
        self.bn            = nn.BatchNorm1d(embed_size)

        # Geler les 6 premiers blocs, laisser libres les 2 derniers
        for param in list(self.resnet.parameters())[:int(len(list(self.resnet.parameters())) * 0.8)]:
            param.requires_grad = fine_tune

    def forward(self, images):

        features = self.resnet(images)                       # (B, 2048, 7, 7)
        features = self.adaptive_pool(features)              # (B, 2048, 1, 1)
        features = features.squeeze(-1).squeeze(-1)          # (B, 2048)
        features = self.bn(self.fc(features))                # (B, embed_size)

        return features

#Q3 : CaptionDecoder (LSTM)


class CaptionDecoder(nn.Module):

    def __init__(
        self,
        embed_size,
        hidden_size,
        vocab_size,
        num_layers = 2,
        dropout    = 0.5
    ):

        super().__init__()

        self.embed = nn.Embedding(
            vocab_size,
            embed_size,
            padding_idx = 0
        )

        self.lstm = nn.LSTM(
            embed_size,
            hidden_size,
            num_layers,
            batch_first = True,
            dropout     = dropout
        )

        self.fc      = nn.Linear(hidden_size, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, features, captions, lengths):

        # features : (B, embed_size) → premier token visuel
        embeddings = self.dropout(self.embed(captions[:, :-1]))

        # Concaténer le vecteur image comme premier token
        inputs = torch.cat(
            [features.unsqueeze(1), embeddings],
            dim = 1
        )

        # Pack pour ignorer le padding
        packed = nn.utils.rnn.pack_padded_sequence(
            inputs,
            lengths.cpu(),
            batch_first    = True,
            enforce_sorted = True
        )

        hiddens, _ = self.lstm(packed)

        hiddens, _ = nn.utils.rnn.pad_packed_sequence(
            hiddens,
            batch_first = True
        )

        return self.fc(hiddens)

#Q3 : Forward pass de vérification des dimensions


EMBED_SIZE   = 256
HIDDEN_SIZE  = 512
VOCAB_SIZE   = len(vocab)
NUM_LAYERS   = 2

encoder = ImageEncoder(embed_size=EMBED_SIZE).to(device)
decoder = CaptionDecoder(
    embed_size  = EMBED_SIZE,
    hidden_size = HIDDEN_SIZE,
    vocab_size  = VOCAB_SIZE,
    num_layers  = NUM_LAYERS
).to(device)

# Batch fictif
images_tmp, captions_tmp, lengths_tmp = next(iter(train_loader))
images_tmp   = images_tmp.to(device)
captions_tmp = captions_tmp.to(device)

features_tmp = encoder(images_tmp)
outputs_tmp  = decoder(features_tmp, captions_tmp, lengths_tmp)

print("=== Vérification des dimensions ===")
print(f"Images entrée    : {images_tmp.shape}")
print(f"Features encoder : {features_tmp.shape}   (B, embed_size)")
print(f"Captions         : {captions_tmp.shape}")
print(f"Sorties decoder  : {outputs_tmp.shape}   (B, T, vocab_size)")

enc_params = sum(p.numel() for p in encoder.parameters() if p.requires_grad)
dec_params = sum(p.numel() for p in decoder.parameters() if p.requires_grad)
print(f"\nParams encoder : {enc_params:,}")
print(f"Params decoder : {dec_params:,}")

# Q4 : Fonctions train / validate + perplexité


criterion = nn.CrossEntropyLoss(ignore_index=0)


def train_caption_epoch(encoder, decoder, loader, optimizer, device):

    encoder.train()
    decoder.train()

    total_loss = 0

    for images, captions, lengths in tqdm(loader, leave=False):

        images   = images.to(device)
        captions = captions.to(device)

        # Teacher Forcing : on donne la vraie caption en entrée
        features = encoder(images)
        outputs  = decoder(features, captions, lengths)

        # Aligner sorties et cibles
        targets = captions[:, 1:]
        T = min(outputs.size(1), targets.size(1))

        loss = criterion(
            outputs[:, :T].reshape(-1, outputs.size(-1)),
            targets[:, :T].reshape(-1)
        )

        optimizer.zero_grad()
        loss.backward()

        # Gradient clipping
        nn.utils.clip_grad_norm_(decoder.parameters(), max_norm=5.0)

        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)


def validate_caption(encoder, decoder, loader, device):

    encoder.eval()
    decoder.eval()

    total_loss = 0

    with torch.no_grad():

        for images, captions, lengths in loader:

            images   = images.to(device)
            captions = captions.to(device)

            features = encoder(images)
            outputs  = decoder(features, captions, lengths)

            targets = captions[:, 1:]
            T = min(outputs.size(1), targets.size(1))

            loss = criterion(
                outputs[:, :T].reshape(-1, outputs.size(-1)),
                targets[:, :T].reshape(-1)
            )

            total_loss += loss.item()

    return total_loss / len(loader)

#Q4 : Entraînement CNN-LSTM (20 epochs)


optimizer_cap = torch.optim.Adam(
    list(encoder.parameters()) +
    list(decoder.parameters()),
    lr = 3e-4
)

scheduler_cap = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_cap,
    mode    = 'min',
    factor  = 0.5,
    patience = 3
)

best_loss_cap = float('inf')
train_losses_cap = []
val_losses_cap   = []
perplexities     = []
NUM_EPOCHS_CAP   = 20

for epoch in range(NUM_EPOCHS_CAP):

    train_loss = train_caption_epoch(
        encoder, decoder, train_loader, optimizer_cap, device
    )

    val_loss = validate_caption(
        encoder, decoder, val_loader, device
    )

    scheduler_cap.step(val_loss)

    train_losses_cap.append(train_loss)
    val_losses_cap.append(val_loss)

    perplexity = np.exp(val_loss)
    perplexities.append(perplexity)

    print(
        f"Epoch [{epoch+1:02d}/{NUM_EPOCHS_CAP}]  "
        f"Train={train_loss:.4f}  "
        f"Val={val_loss:.4f}  "
        f"Perplexité={perplexity:.2f}"
    )

    if val_loss < best_loss_cap:
        best_loss_cap = val_loss
        torch.save(encoder.state_dict(), "best_encoder.pth")
        torch.save(decoder.state_dict(), "best_decoder.pth")

# Courbe de perplexité
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(train_losses_cap, label='Train', color='steelblue')
axes[0].plot(val_losses_cap,   label='Val',   color='orange')
axes[0].set_title("Q4 — Loss CNN-LSTM")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss")
axes[0].legend()
axes[0].grid()

axes[1].plot(perplexities, color='green')
axes[1].set_title("Q4 — Perplexité (Val)")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Perplexité")
axes[1].grid()

plt.tight_layout()
plt.show()

print(f"\nMeilleure perplexité : {min(perplexities):.2f}")

#Q5 : Greedy Search


def greedy_caption(encoder, decoder, image, vocab, max_len=50, device='cpu'):

    encoder.eval()
    decoder.eval()

    with torch.no_grad():

        feature = encoder(
            image.unsqueeze(0).to(device)
        )                                      # (1, embed_size)

        # Initialiser avec le token SOS
        inputs  = feature.unsqueeze(1)         # (1, 1, embed_size)
        hidden  = None
        words   = []

        for _ in range(max_len):

            out, hidden = decoder.lstm(inputs, hidden)

            logits      = decoder.fc(out.squeeze(1))
            pred        = logits.argmax(dim=-1)

            word = vocab.itos.get(pred.item(), '<UNK>')

            if word == '<EOS>':
                break

            if word not in ('<SOS>', '<PAD>'):
                words.append(word)

            inputs = decoder.embed(pred).unsqueeze(1)

    return ' '.join(words)

#Q5 : Beam Search


def beam_search_caption(
    encoder,
    decoder,
    image,
    vocab,
    beam_size = 3,
    max_len   = 50,
    device    = 'cpu'
):

    encoder.eval()
    decoder.eval()

    with torch.no_grad():

        feature = encoder(image.unsqueeze(0).to(device))  # (1, embed_size)

        # beams : (score, sequence, hidden_state)
        beams     = [(0.0, [vocab.stoi['<SOS>']], None)]
        completed = []

        for _ in range(max_len):

            new_beams = []

            for score, seq, hidden in beams:

                last_word = torch.tensor(
                    [[seq[-1]]]
                ).to(device)

                embed = decoder.embed(last_word)   # (1, 1, embed)

                if hidden is None:
                    inp = torch.cat(
                        [feature.unsqueeze(1), embed],
                        dim = 1
                    )
                    out, hidden = decoder.lstm(inp)
                    out = out[:, -1:]
                else:
                    out, hidden = decoder.lstm(embed, hidden)

                logprobs = F.log_softmax(
                    decoder.fc(out.squeeze(1)),
                    dim = -1
                )

                topk_scores, topk_ids = logprobs.topk(beam_size)

                for s, idx in zip(topk_scores[0], topk_ids[0]):

                    new_seq   = seq + [idx.item()]
                    new_score = score + s.item()

                    if idx.item() == vocab.stoi['<EOS>']:
                        completed.append(
                            (new_score / len(new_seq), new_seq)
                        )
                    else:
                        new_beams.append(
                            (
                                new_score,
                                new_seq,
                                (hidden[0].clone(), hidden[1].clone())
                            )
                        )

            beams = sorted(
                new_beams,
                key     = lambda x: x[0] / len(x[1]),
                reverse = True
            )[:beam_size]

            if not beams:
                break

        best = max(
            completed or [(0, beams[0][1])],
            key = lambda x: x[0]
        )

        return ' '.join([
            vocab.itos.get(i, '<UNK>')
            for i in best[1][1:-1]
        ])

#Q5 : Comparaison Greedy vs Beam Search sur 5 images


encoder.load_state_dict(
    torch.load("best_encoder.pth", map_location=device)
)
decoder.load_state_dict(
    torch.load("best_decoder.pth", map_location=device)
)

# Prendre 5 images du val_loader
images_val, captions_val, _ = next(iter(val_loader))

fig, axes = plt.subplots(5, 1, figsize=(14, 25))

for i in range(5):

    img = images_val[i]

    greedy_cap = greedy_caption(encoder, decoder, img, vocab, device=device)
    beam_cap   = beam_search_caption(
        encoder, decoder, img, vocab, beam_size=3, device=device
    )

    gt_cap = ' '.join([
        vocab.itos.get(idx.item(), '<UNK>')
        for idx in captions_val[i]
        if idx.item() not in [
            vocab.stoi['<PAD>'],
            vocab.stoi['<SOS>'],
            vocab.stoi['<EOS>']
        ]
    ])

    img_np = img.permute(1, 2, 0).numpy()
    img_np = img_np * np.array([0.229, 0.224, 0.225]) \
                    + np.array([0.485, 0.456, 0.406])

    axes[i].imshow(np.clip(img_np, 0, 1))
    axes[i].set_title(
        f"GT     : {gt_cap}\n"
        f"Greedy : {greedy_cap}\n"
        f"Beam   : {beam_cap}",
        fontsize = 9,
        loc      = 'left'
    )
    axes[i].axis('off')

plt.suptitle("Q5 — Greedy vs Beam Search (beam=3)", fontsize=13)
plt.tight_layout()
plt.show()

#Q5 : Score BLEU-4 sur le jeu de validation


def compute_bleu4(encoder, decoder, loader, vocab, device, beam=False):

    encoder.eval()
    decoder.eval()

    references  = []
    hypotheses  = []

    with torch.no_grad():

        for images, captions, _ in tqdm(loader, desc="BLEU-4"):

            for i in range(images.size(0)):

                img = images[i]

                if beam:
                    hyp = beam_search_caption(
                        encoder, decoder, img, vocab,
                        beam_size=3, device=device
                    )
                else:
                    hyp = greedy_caption(
                        encoder, decoder, img, vocab, device=device
                    )

                # Référence (caption GT de la batch)
                ref = [
                    vocab.itos.get(idx.item(), '<UNK>')
                    for idx in captions[i]
                    if idx.item() not in [
                        vocab.stoi['<PAD>'],
                        vocab.stoi['<SOS>'],
                        vocab.stoi['<EOS>']
                    ]
                ]

                references.append([ref])
                hypotheses.append(hyp.split())

    smooth = SmoothingFunction().method1
    bleu4  = corpus_bleu(references, hypotheses, smoothing_function=smooth)

    return bleu4


print("Calcul BLEU-4 Greedy...")
bleu4_greedy = compute_bleu4(
    encoder, decoder, val_loader, vocab, device, beam=False
)

print("Calcul BLEU-4 Beam Search...")
bleu4_beam = compute_bleu4(
    encoder, decoder, val_loader, vocab, device, beam=True
)

print(f"\nBLEU-4 Greedy     : {bleu4_greedy:.4f}")
print(f"BLEU-4 Beam (k=3) : {bleu4_beam:.4f}")

print("""
Observations Q5 :
  Beam Search donne généralement de meilleures captions que Greedy
  car il explore plusieurs hypothèses simultanément et choisit
  la séquence avec le score log-probabilité normalisé le plus élevé.
  La différence qualitative est surtout visible sur les captions
  longues où Greedy peut bloquer sur des mots répétitifs.
""")

